### ISSUE TITLE
💡Ideas

### ISSUE THREAD

**Issue by jd-apprentice** [jd-apprentice/dbn-tools#5]
- [ ] Build a Dockerfile
- [ ] Installation for Fedora
- [ ] Implement another package functionability for example -> [file-uploader](https://github.com/jd-apprentice/file-uploader)
- [ ] Another functionability like -> [youtube-dl](https://itsfoss.com/download-youtube-linux/)
- [ ] Another example could be -> [image-manager](https://github.com/jd-apprentice/image-manager-cli)
- [ ] Currency display -> [usd-ars](https://github.com/jd-apprentice/cli-currency)
- [ ] Read documentation for multiple languages from the terminal

**Comment by jd-apprentice** [comment]
- [x] Currency display was implemented in #11 and a new release is up (0.0.5)

**Comment by jd-apprentice** [comment]
- [x] Build a Dockerfile was implemented in #14

**Comment by jd-apprentice** [comment]
- [x] Another functionability like -> [youtube-dl](https://itsfoss.com/download-youtube-linux/) was done on #18

**Comment by jd-apprentice** [comment]
Sort of sub-menues are being worked rn first approach closed at #21

**Comment by jd-apprentice** [comment]
#28 and #29 had some improvements for the code quality of the project

![image](https://user-images.githubusercontent.com/68082746/216807270-57dd69e7-187c-4bf5-becd-e488e2a1f989.png)

codacy report is now at 0 issues (1 high error and pr won't be qualified)
